{{- range $serviceName, $service := .Values.services }}
{{- if and ($service.enabled | default true) ($service.awsSecrets) }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $serviceName }}-secrets
  namespace: {{ $service.namespace.name | default "default" }}
spec:
  provider: aws
  parameters:
    objects: |
      {{- range $service.awsSecrets }}
      - objectName: "{{ tpl .secretName $ }}"
        objectType: "secretsmanager"
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: {{ .path | quote }}
            objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
  secretObjects:
  - secretName: {{ $serviceName }}-secrets
    type: Opaque
    data:
    {{- range $service.awsSecrets }}
    {{- range .jmesPath }}
    - objectName: {{ .objectAlias | quote }}
      key: {{ .key | quote }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
