{{- range $serviceName, $service := .Values.services }}
{{- if and ($service.enabled | default true) ($service.serviceAccount) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-sa
  namespace: {{ $service.namespace.name | default "default" }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $.Values.awsAccountNumber }}:role/{{ $.Values.environment }}-{{ $service.serviceAccount.roleName }}
  labels:
    app: {{ $serviceName }}
    environment: {{ $.Values.environment }}
{{- end }}
{{- end }}
