{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled | default true }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $service.namespace.name | default "default" }}
  labels:
    app: {{ $serviceName }}
    environment: {{ $.Values.environment }}
spec:
  type: {{ $service.serviceType | default "ClusterIP" }}
  selector:
    app: {{ $serviceName }}
  ports:
  - port: {{ $service.servicePort | default 80 }}
    targetPort: {{ $service.containerPort | default 80 }}
    protocol: TCP
    name: http
{{- end }}
{{- end }}
